# Utiliza la imagen base de .NET Core SDK 6 para construir la aplicación
FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build-env
WORKDIR /app

# Copia los archivos de proyecto y restaura las dependencias
COPY *.csproj ./
RUN dotnet restore

# Copia el resto de los archivos de la aplicación
COPY . ./

# Copia los archivos del proyecto DB
COPY ../DB/*.csproj ../DB/
RUN dotnet restore ../DB/*.csproj

# Compila la aplicación, incluyendo el proyecto DB
RUN dotnet publish -c Release -o out --no-restore

# Utiliza la imagen base de .NET Core para ejecutar la aplicación
FROM mcr.microsoft.com/dotnet/aspnet:6.0
WORKDIR /app
COPY --from=build-env /app/out .

# Copia el archivo appsettings.json
COPY appsettings.json .

# Expone el puerto en el que se ejecutará la aplicación
EXPOSE 8085

# Inicia la aplicación cuando se ejecute el contenedor
ENTRYPOINT ["dotnet", "MicroservicioCatalogos.dll"]
